name: .NET Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
   
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '8.0.x'

    - name: Restore NuGet Packages
      run: nuget restore Strafenkatalog_CSharp.sln

    - name: Build solution
      run: dotnet build -c Debug
      
# Uncomment these lines if you want to run tests
#    - name: Run tests (NET Framework)
#      run: vstest.console.exe YourTestProject.dll
