name: .NET Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Display Runner Info
      run: systeminfo

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet Packages
      run: dotnet restore Kegelkasse/Kegelkasse.csproj

    - name: Build and publish project
      run: dotnet publish Kegelkasse/Kegelkasse.csproj -c Release -r win-x64 --self-contained=false -o /publish

#    - name : Run Unit Tests   
#      run: dotnet test Kegelkasse.sln -c Release -r win-x64 --verbosity minimal --no-build --no-restore /p:EnableWindowsTargeting=true

    - name: Upload publish folder
      uses: actions/upload-artifact@v4
      with:
        name: Kegelkasse-publish
        path: ./publish
