name: .NET Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Display Runner Info
      run: systeminfo

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet Packages
      run: dotnet restore Strafenkatalog/Strafenkatalog.csproj

    - name: Build and publish project
      run: dotnet publish Strafenkatalog/Strafenkatalog.csproj -c Release -r win-x64 --self-contained=false -o /app

    - name : Run Unit Tests   
      run: dotnet test -c Release --verbosity minimal --no-build --no-restore /p:EnableWindowsTargeting=true

    - name: Create Docker Image
      run: docker build -t morpheus061986/strafenkatalog:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Push Docker Image
      run: docker push morpheus061986/strafenkatalog:latest
