name: .NET Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
   
    steps:
    - name: Display Runner Info
      run: uname -a
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '8.0.x'

    - name: Restore NuGet Packages
      run: dotnet restore Strafenkatalog_CSharp.sln /p:EnableWindowsTargeting=true

    - name: Build solution
      run: dotnet build -c Release Strafenkatalog_CSharp.sln /p:EnableWindowsTargeting=true

    - name: Create Docker Image
      run: docker build -t morpheus061986/strafenkatalog:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push morpheus061986/strafenkatalog:latest
